Feature/yourtips phase2
praekeltfoundation/molo.yourtips pull request #6
Opened 2017-06-29 14:55 UTC by cblignaut

@saeedmb8: Here is Phase 2's PR, I will merge this after we completed Phase 1's PR.

2017-07-05 17:55 UTC, saeedmb8 commented on .travis.yml
> +  - molo scaffold testapp --include=molo.yourtips ^yourtips/ --include=likes ^likes/
@cblignaut is there any specific reason that we are not including the likes URL in the urls.py, instead of adding it here?

2017-07-05 18:01 UTC, saeedmb8 commented on molo/yourtips/models.py
> +                'you can share with other youth on relationships?',
Can we add the default text in the template instead, this text needs to be in a trans block so we can get the translation for it.

2017-07-05 18:05 UTC, saeedmb8 commented on molo/yourtips/templates/yourtips/your_tips_create_tip_on_homepage.html
> -  </h4>
as I mentioned above lets keep this text here

2017-07-05 18:06 UTC, saeedmb8 commented on molo/yourtips/templates/yourtips/your_tips_section_menu.html
> +        <!--Menu description - From CMS?-->
?

2017-07-05 18:09 UTC, smarzban requested changes
left some small comments otherwise looks great

2017-07-06 07:19 UTC, cblignaut commented on molo/yourtips/templates/yourtips/your_tips_section_menu.html
> +        <!--Menu description - From CMS?-->
Mitso added this, I removed this template on the next refactor PR.

2017-07-06 07:56 UTC, cblignaut commented on .travis.yml
> +  - molo scaffold testapp --include=molo.yourtips ^yourtips/ --include=likes ^likes/
I tested adding it to the yourtips urls, the issue is testing locally (py.test) and with travis. This was the only way I could get both to work with the url namespace.

2017-07-06 07:56 UTC, cblignaut commented
@saeedmb8: Thanks I replied to your comments.

2017-07-06 08:32 UTC, saeedmb8 commented on .travis.yml
> +  - molo scaffold testapp --include=molo.yourtips ^yourtips/ --include=likes ^likes/
👍

2017-07-06 11:55 UTC, cblignaut commented
@saeedmb8: Could you please check this again if you have time ?

2017-07-06 13:11 UTC, smarzban approved these changes

2017-07-06 13:25 UTC, merged